// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHc0WMg0gQ0QFMSHinIe8Ixirk8qYi7jE',
    appId: '1:70341955970:web:7928e1ca9d548cb85fff9b',
    messagingSenderId: '70341955970',
    projectId: 'remindme-fbf1f',
    authDomain: 'remindme-fbf1f.firebaseapp.com',
    storageBucket: 'remindme-fbf1f.appspot.com',
    measurementId: 'G-KVLNQM3EWT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNpcVCa0TflMQtaY772NcQMq3ovS_gl30',
    appId: '1:70341955970:ios:e77cb06dadce1a255fff9b',
    messagingSenderId: '70341955970',
    projectId: 'remindme-fbf1f',
    storageBucket: 'remindme-fbf1f.appspot.com',
    iosBundleId: 'com.example.remindme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNpcVCa0TflMQtaY772NcQMq3ovS_gl30',
    appId: '1:70341955970:ios:e77cb06dadce1a255fff9b',
    messagingSenderId: '70341955970',
    projectId: 'remindme-fbf1f',
    storageBucket: 'remindme-fbf1f.appspot.com',
    iosBundleId: 'com.example.remindme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHc0WMg0gQ0QFMSHinIe8Ixirk8qYi7jE',
    appId: '1:70341955970:web:276611f3531b2b195fff9b',
    messagingSenderId: '70341955970',
    projectId: 'remindme-fbf1f',
    authDomain: 'remindme-fbf1f.firebaseapp.com',
    storageBucket: 'remindme-fbf1f.appspot.com',
    measurementId: 'G-2S4REPD7M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zFlnwvFHE3cHgVSqlQXZM_pJEU7Ja6o',
    appId: '1:70341955970:android:1813894fd53952d95fff9b',
    messagingSenderId: '70341955970',
    projectId: 'remindme-fbf1f',
    storageBucket: 'remindme-fbf1f.appspot.com',
  );

}